### ISSUE TITLE
u-boot for Sunchip_SDK-758

### ISSUE THREAD

**Issue by ricardojlrufino** [ade-ma/A20Notes#14]
Hello, I wonder if you have the u-boot for that device:

http://linux-sunxi.org/Sunchip_SDK-758

Thank U

**Comment by itdaniher** [comment]
Pull request at https://github.com/linux-sunxi/u-boot-sunxi/pull/80.

Let me know if you need a binary or something.

Regards!
Ian

**Comment by ricardojlrufino** [comment]
Perfect , Thank U.

## Ricardo JL Rufino

CriativaSoft http://www.criativasoft.com.br -
_Desenvolvimento de Sistemas com QualidadeAnalista e Engenheiro de Software_
_Skype_: ricardojlrufino
_Linkedin_: br.linkedin.com/pub/ricardo-rufino/5a/696/81a
ricardo.jl.rufino@gmail.com

2015-01-16 0:39 GMT-03:00 Ian Daniher notifications@github.com:
